<<<<<<< HEAD
version: '3'
=======
>>>>>>> develop
services:
  nginx:
    build:
       dockerfile: ./Dockerfilenginx
       context: .
<<<<<<< HEAD
    image: rogerramossilva/nginx
=======
    image: rogerramossilva/nginx:1.0
>>>>>>> develop
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - redelocal
    depends_on:
      - "web1"
      - "web2"
      - "web3"
  db:
    build:
      dockerfile: ./Dockerfiledb
      context: .
    image: rogerramossilva/db
    container_name: db
    networks:
      - redelocal
    ports: 
      - "3306"

  web1:
    build:
       dockerfile: ./Dockerfileweb
       context: .
    image: rogerramossilva/web
    container_name: web1
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web2: 
    image: rogerramossilva/web
    container_name: web2
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web3: 
    image: rogerramossilva/web
    container_name: web3
    ports:
      - "80"
    networks:
      - redelocal 
    depends_on:
      - "db"  
    
networks:
  redelocal:
    driver: bridge
